On-the-fly shooting - untested
fairviewrobotics/2024-robot-code pull request #23
Opened 2024-02-11 17:43 UTC by aaditsangvikar

Gravity is really annoying

This is an untested version of the on-the-fly shooting system. At the moment, it currently only takes into account about movement toward and away from the speaker, and not lateral movement. It also contains values for shooter angle, height, speed, etc, that need to be tuned.

2024-02-14 06:15 UTC, zaneal requested changes
This looks like a good jumping off point. There are still some things that need to be tested and redone, but overall this is great. Nice job getting this done so quick. Hopefully these changes can be made in preparation for getting the robot, and once gotten, made before Coronado.

There wasn't any documentation throughout this code. I know we don't have much time, but having documentation would have made this much easier to understand and I'm sure will make it a lot easier for comprehension later on. If you get a free moment, please start to add documentation.

2024-02-14 06:15 UTC, zanealoia commented on src/main/java/frc/robot/constants/ShooterConstants.java
> +    public static final double shooterHeight = 0.5;
Lets also consider the fact that the speaker has a barrier in front of it, meaning shots can not go in at any angle

2024-02-14 06:15 UTC, zanealoia commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +        bottomMotor.setIdleMode(CANSparkBase.IdleMode.kCoast);
Yes, please keep these in coast and not break as they were for part of testing. It will be better for the motors and for reducing spin up time depending on how fast our cycles are

2024-02-14 06:15 UTC, zanealoia commented on src/main/java/frc/robot/constants/ShooterConstants.java
> +    public static final double sweetSpotDistance = 3.0;
Im assuming this is just a guess of what we will test in the future to be our ideal spot? Also is it currently even being used?

2024-02-14 06:15 UTC, zanealoia commented on src/main/java/frc/robot/RobotContainer.java
Obviously these changes on the file don't need to be here, however we can disregard it for now or you can take it out of your commit and only keep it locally.

2024-02-14 06:15 UTC, zaneal commented on src/main/java/frc/robot/commands/SpinUpCommand.java
Let's consider advancing this. Having a backup spin up is always good if more advanced commands don't work. However, we should add the following in a separate command:
The spin up should start automatically(if say the secondary driver says we want to go for speaker). Based on data we create and the computer receives, it should be relatively easy for use to calculate an average curve or line of rpm and time to find how long it will take us to get to 6500 from any current speed. We can read the speed of our shooter currently(in case we are fast enough that it hasn't fully stopped yet). Then we can incorporate path planner or another distance measurement to figure out the distance and time to our shooter area. After that, we simply start the spin up once a line break is detected, and add 1-2 seconds of backup spin-up time. Then our robot should always spin up perfectly ahead of shooting if we are going for the speaker and have a note.

2024-02-14 06:15 UTC, zaneal commented on src/main/java/frc/robot/constants/ShooterConstants.java
> +    public static final double shooterAngle = Math.toRadians(45);
Option for advancement: calculate the ideal angle of our shooter based on how it performs and what gives us the best results with what we have(basically what gets us the farthest back)

2024-02-14 06:15 UTC, zaneal commented on src/main/java/frc/robot/constants/ShooterConstants.java
> +    public static final double shooterI = 0.0;
This is always good to have, although with our current time crunch and good shooter performance, lets hold off on tuning PID till after Coronado or Utah.

2024-02-14 06:15 UTC, zaneal commented on src/main/java/frc/robot/commands/SpeakerCommand.java
Obviously let's wait to push until this is tested and tuned, but it looks like a good start. We can brainstorm more ways to advance this later on.

2024-02-14 06:15 UTC, zaneal commented on src/main/java/frc/robot/commands/SpeakerCommand.java
> +            shootingDistanceFromSpeaker -= noteSpeedX * ShooterConstants.shootDelayTime;
Im assuming this delay time if accounting for the delay to move the note from the indexer to the shooter. If it is not, that time needs to be considered for.

2024-02-17 17:33 UTC, ddjoshua01 commented on src/main/java/frc/robot/commands/AmpCommand.java
> +     * Moves the indexer to the amp and scores
Hopefully

2024-02-17 22:48 UTC, merged