Swerve Subsystem Documentation + Stufff!!!!
fairviewrobotics/2024-robot-code pull request #7
Opened 2024-01-10 02:39 UTC by ddjoshua01

Wooo comments

2024-01-11 14:48 UTC, acuaroo approved these changes
Fine, but remember comments shouldn't just describe the code, it should give a why. 

You've done this in some places, but in others, comments are just redundant.

2024-01-12 00:49 UTC, aaditsangvikar requested changes
You changed some telemetry code...? Not sure if this was an accident, but in the setting of network tables odometry, you switched a frontRight to a frontLeft. 

Relating to the comments, they look pretty good, but you don't need to switch stuff like "Set Network Tables Telemetry" to "Set telemetry in network tables".

I think it would be best if you left the previous comments that were already there untouched, and added your own descriptions below them, or something like that.

2024-01-12 00:51 UTC, ddjoshua01 commented
Oh shoot, I deleted the wrong thing. I’ll fix that and improve the comments.

2024-01-12 17:26 UTC, TotalTaxAmount requested changes
Looks good, just add the javadoc  entries for the functions

2024-01-12 17:26 UTC, TotalTaxAmount commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
>      public void drive(double forwardMetersPerSecond, double sidewaysMetersPerSecond, double radiansPerSecond, boolean fieldRelative, boolean rateLimit) {
Above all functions please add a javadoc entry so in the future we can generate readable documentation for out code. 
[How to write javadoc](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)

2024-01-17 00:09 UTC, acuaroo requested changes
Looks good! Just add @return to the Javadoc stuff when it's not void.

2024-01-17 00:10 UTC, merged